version: "3.9"
services:
  varnish:
    image: "varnish:latest"
    ports:
    - "8080:80"
    volumes:
    - ./varnish/default.vcl:/etc/varnish/default.vcl
  cms-app:
    image: "webratio/nodejs-http-server"
    expose:
    - "9001"
    ports:
      - "9001:9001"
    volumes:
      - ./cms-app:/opt/www
    environment:
      PORT: 9001
  news-app:
    image: "nextjs:latest"
    command: ash -c "npx next build && npx next start -p 9002"
    expose:
      - "9002"
    ports:
      - "9002:9002"
    volumes:
      - ./news-app/pages:/usr/src/pages
      - ./news-app/next.config.js:/usr/src/next.config.js
      - ./news-app/.babelrc:/usr/src/.babelrc
    environment:
      - PORT=9002
      - NODE_ENV=production
      - NEXT_PUBLIC_NEWS_API=http://mock-api-app:9003
  mock-api-app:
    image: "json-server:latest"
    command: ash -c "json-server --watch index.js --port 9003 --host 0.0.0.0"
    expose:
      - "9003"
    ports:
      - "9003:9003"
    volumes:
      - ./mock-api-app/data:/usr/src/data
      - ./mock-api-app/index.js:/usr/src/index.js
    environment:
      - PORT=9003
